version: '2.3'
services:
  kalki-main-controller:
    image: kalki/kalki-main-controller
    container_name: kalki-main-controller
    network_mode: "host"
    environment:
      - TZ=${HOST_TZ}
    command: ${CMD_PARAMS}
    volumes:
      - ./kmc-logs:/logs
