#!/bin/bash
echo Exporting JAVA_HOME
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-12.0.1.jdk/Contents/Home/
echo $JAVA_HOME
echo Compiling C Library...
gcc -I"$JAVA_HOME/include" -I"$JAVA_HOME/include/darwin" -dynamiclib -o libfsm.dylib FSM.c
echo Compiling Java code...
echo UNTS...
javac -h . UNTS.java
echo Done
echo PHLE...
javac -h . PHLE.java
echo Done
echo DLC...
javac -h . DLC.java
echo Done
echo Launcher...
javac -h . Launcher.java
echo Done
echo Testbench...
javac -h . LauncherDeviceTestBench.java
echo All Finished