/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_cmu_sei_kalki_controller_fsm_UNTSStateMachine */

#ifndef _Included_edu_cmu_sei_kalki_controller_fsm_UNTSStateMachine
#define _Included_edu_cmu_sei_kalki_controller_fsm_UNTSStateMachine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_cmu_sei_kalki_controller_fsm_UNTSStateMachine
 * Method:    generateNextState
 * Signature: ()V
 */
JNIEXPORT jintArray JNICALL Java_edu_cmu_sei_kalki_controller_fsm_UNTSStateMachine_generateNextState
  (JNIEnv *, jobject, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
