/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_cmu_sei_ttg_kalki_controller_JavaDevices_ROOMBAStateMachine */

#ifndef _Included_edu_cmu_sei_ttg_kalki_controller_JavaDevices_ROOMBAStateMachine
#define _Included_edu_cmu_sei_ttg_kalki_controller_JavaDevices_ROOMBAStateMachine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_cmu_sei_ttg_kalki_controller_JavaDevices_ROOMBAStateMachine
 * Method:    generateNextState
 * Signature: ()V
 */
JNIEXPORT jintArray JNICALL Java_edu_cmu_sei_ttg_kalki_controller_JavaDevices_ROOMBAStateMachine_generateNextState
  (JNIEnv *, jobject, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
