/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_cmu_sei_ttg_kalki_controller_JavaDevices_UNTSStateMachine */

#ifndef _Included_edu_cmu_sei_ttg_kalki_controller_JavaDevices_UNTSStateMachine
#define _Included_edu_cmu_sei_ttg_kalki_controller_JavaDevices_UNTSStateMachine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_cmu_sei_ttg_kalki_controller_JavaDevices_UNTSStateMachine
 * Method:    generateNextState
 * Signature: ()V
 */
JNIEXPORT int JNICALL Java_edu_cmu_sei_ttg_kalki_controller_JavaDevices_UNTSStateMachine_generateNextState
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
