/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_cmu_sei_ttg_kalki_controller_JavaDevices_VIZIOTVStateMachine */

#ifndef _Included_edu_cmu_sei_ttg_kalki_controller_JavaDevices_VIZIOTVStateMachine
#define _Included_edu_cmu_sei_ttg_kalki_controller_JavaDevices_VIZIOTVStateMachine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_cmu_sei_ttg_kalki_controller_JavaDevices_VIZIOTVStateMachine
 * Method:    generateNextState
 * Signature: ()V
 */
JNIEXPORT jintArray JNICALL Java_edu_cmu_sei_ttg_kalki_controller_JavaDevices_VIZIOTVStateMachine_generateNextState
  (JNIEnv *, jobject, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
