/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_cmu_sei_ttg_kalki_controller_DeviceStateMachines_DLCStateMachine */

#ifndef _Included_edu_cmu_sei_ttg_kalki_controller_DeviceStateMachines_DLCStateMachine
#define _Included_edu_cmu_sei_ttg_kalki_controller_DeviceStateMachines_DLCStateMachine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_cmu_sei_ttg_kalki_controller_DeviceStateMachines_DLCStateMachine
 * Method:    generateNextState
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_sei_ttg_kalki_controller_DeviceStateMachines_DLCStateMachine_generateNextState
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
